name: flask_flutter_app
description: A Flutter application that interacts with a Flask backend for image uploads and OpenAI API calls.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^0.8.4+3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/